apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inject-container-webhook-tls
  namespace: tools
spec:
  secretName: inject-container-webhook-tls
  privateKey:
    rotationPolicy: Always
  commonName: inject-container-webhook.cluster.local
  dnsNames:
    - inject-container-webhook.cluster.local
    - inject-container-webhook.tools.svc
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  duration: 43800h # 5y
  renewBefore: 168h # 7d
