apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-project
  namespace: tools
spec:
  secretName: webhook-project
  privateKey:
    rotationPolicy: Always
  commonName: webhook-project.cluster.local
  dnsNames:
    - webhook-project.cluster.local
    - webhook-project.tools.svc
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  duration: 43800h # 5y
  renewBefore: 168h # 7d
