---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inject-container-webhook
  namespace: tools
data:
  initcontainers.yaml: |
    - name: some-container
      image: some-container:0.1
      env:
        - name: SOME-VARIABLE
          value: somevariablecontent
  sidecarcontainers.yaml: |
    []
