apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-project
  namespace: tools
  labels:
    app: webhook-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-project
  template:
    metadata:
      labels:
        app: webhook-project
    spec:
      containers:
        - name: webhook-project
          image: artifactory.cicd.ocean.pmicloud.biz/docker/doplat/webhook-project:latest
          ports:
            - containerPort: 8443
          resources:
            limits:
              cpu: 600m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: LOG_LEVEL
              value: INFO
          volumeMounts:
            - name: certificate
              mountPath: /app/ssl
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8443
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8443
      volumes:
        - name: certificate
          secret:
            secretName: webhook-project
      hostNetwork: true
      serviceAccountName: webhook-project
