apiVersion: apps/v1
kind: Deployment
metadata:
  name: inject-container-webhook
  namespace: tools
  labels:
    app: inject-container-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inject-container-webhook
  template:
    metadata:
      labels:
        app: inject-container-webhook
    spec:
      containers:
        - name: inject-container-webhook
          image: inject-container-webhook:latest
          ports:
            - containerPort: 8443
          resources:
            limits:
              cpu: 600m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: LOG_LEVEL
              value: DEBUG
          volumeMounts:
            - name: certificate
              mountPath: /app/ssl
              readOnly: true
            - name: inject-container-webhook-config
              mountPath: /app/config
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8443
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8443
      volumes:
        - name: certificate
          secret:
            secretName: inject-container-webhook-tls
        - name: inject-container-webhook-config
          configMap:
            name: inject-container-webhook
            items:
              - key: initcontainers.yaml
                path: initcontainers.yaml
              - key: sidecarcontainers.yaml
                path: sidecarcontainers.yaml
      serviceAccountName: inject-container-webhook
      hostNetwork: true
