apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-project
  namespace: tools
  labels:
    component: mutating-controller
  annotations:
    cert-manager.io/inject-ca-from: tools/webhook-project
webhooks:
  - name: webhook-project.cluster.local
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        use: dsproject
    clientConfig:
      service:
        name: webhook-project
        namespace: tools
        path: /mutate/pods
        port: 8443
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
